// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Section 7.5.6. Acknowledge the receipt of a start/resume, stop/freeze, or RemoveEntityPDU. COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Section 7.5.6. Acknowledge the receipt of a start/resume, stop/freeze, or RemoveEntityPDU. COMPLETE */
public class AcknowledgePduTest {
  public AcknowledgePduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.AcknowledgePdu openDis = new edu.nps.moves.dis7.AcknowledgePdu();
    com.phyzicsz.dis7.AcknowledgePdu dis = new AcknowledgePdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
