/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 7.5.6. Acknowledge the receipt of a start/resume, stop/freeze, or
 * RemoveEntityPDU. COMPLETE
 */
public class AcknowledgePduTest {

	@Test
	public void testAcknowledgePdu() {
	}
}