/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 5.3.12.5: Ack receipt of a start-resume, stop-freeze, create-entity
 * or remove enitty (reliable) pdus. COMPLETE
 */
public class AcknowledgeReliablePduTest {

	@Test
	public void testAcknowledgeReliablePdu() {
	}
}