/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * information about a specific UA emmtter. Section 6.2.2.
 */
public class AcousticEmitterTest {

	@Test
	public void testAcousticEmitter() {
	}
}