// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
//  information about a specific UA emmtter. Section 6.2.2.
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 *  information about a specific UA emmtter. Section 6.2.2. */
public class AcousticEmitterTest {
  public AcousticEmitterTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.AcousticEmitter openDis = new edu.nps.moves.dis7.AcousticEmitter();
    com.phyzicsz.dis7.AcousticEmitter dis = new AcousticEmitter();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
