// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Section 5.3.12.6: request from a simulation manager to a managed entity to perform a specified action. COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Section 5.3.12.6: request from a simulation manager to a managed entity to perform a specified action. COMPLETE */
public class ActionRequestReliablePduTest {
  public ActionRequestReliablePduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.ActionRequestReliablePdu openDis = new edu.nps.moves.dis7.ActionRequestReliablePdu();
    com.phyzicsz.dis7.ActionRequestReliablePdu dis = new ActionRequestReliablePdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
