/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 5.3.12.7: Response from an entity to an action request PDU. COMPLETE
 */
public class ActionResponseReliablePduTest {

	@Test
	public void testActionResponseReliablePdu() {
	}
}