/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 7.5.8. response to an action request PDU. COMPLETE
 */
public class ActionResponsePduTest {

	@Test
	public void testActionResponsePdu() {
	}
}