// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Section 7.5.7. Request from simulation manager to a managed entity to perform a specified action. COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Section 7.5.7. Request from simulation manager to a managed entity to perform a specified action. COMPLETE */
public class ActionRequestPduTest {
  public ActionRequestPduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.ActionRequestPdu openDis = new edu.nps.moves.dis7.ActionRequestPdu();
    com.phyzicsz.dis7.ActionRequestPdu dis = new ActionRequestPdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
