// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Section 7.5.8. response to an action request PDU. COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Section 7.5.8. response to an action request PDU. COMPLETE */
public class ActionResponsePduTest {
  public ActionResponsePduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.ActionResponsePdu openDis = new edu.nps.moves.dis7.ActionResponsePdu();
    com.phyzicsz.dis7.ActionResponsePdu dis = new ActionResponsePdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
