/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 5.3.12.6: request from a simulation manager to a managed entity to
 * perform a specified action. COMPLETE
 */
public class ActionRequestReliablePduTest {

	@Test
	public void testActionRequestReliablePdu() {
	}
}