/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 7.5.7. Request from simulation manager to a managed entity to perform
 * a specified action. COMPLETE
 */
public class ActionRequestPduTest {

	@Test
	public void testActionRequestPdu() {
	}
}