// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Specifies the character set used in the first byte, followed by up to 31 characters of text data. Section 6.2.4. 
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Specifies the character set used in the first byte, followed by up to 31 characters of text data. Section 6.2.4.  */
public class AggregateMarkingTest {
  public AggregateMarkingTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.AggregateMarking openDis = new edu.nps.moves.dis7.AggregateMarking();
    com.phyzicsz.dis7.AggregateMarking dis = new AggregateMarking();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
