// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Identifies the type and organization of an aggregate. Section 6.2.5
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Identifies the type and organization of an aggregate. Section 6.2.5 */
public class AggregateTypeTest {
  public AggregateTypeTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.AggregateType openDis = new edu.nps.moves.dis7.AggregateType();
    com.phyzicsz.dis7.AggregateType dis = new AggregateType();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
