/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Identifies the type and organization of an aggregate. Section 6.2.5
 */
public class AggregateTypeTest {

	@Test
	public void testAggregateType() {
	}
}