/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * The unique designation of each aggrgate in an exercise is specified by an
 * aggregate identifier record. The aggregate ID is not an entity and shall not
 * be treated as such. Section 6.2.3.
 */
public class AggregateIdentifierTest {

	@Test
	public void testAggregateIdentifier() {
	}
}