/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Specifies the character set used in the first byte, followed by up to 31
 * characters of text data. Section 6.2.4.
 */
public class AggregateMarkingTest {

	@Test
	public void testAggregateMarking() {
	}
}