/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * The Angle Deception attribute record may be used to communicate discrete
 * values that are associated with angle deception jamming that cannot be
 * referenced to an emitter mode. The values provided in the record records
 * (provided in the associated Electromagnetic Emission PDU). (The victim radar
 * beams are those that are targeted by the jammer.) Section 6.2.21.2.2
 */
public class AngleDeceptionTest {

	@Test
	public void testAngleDeception() {
	}
}