/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Angular velocity measured in radians per second out each of the entity's own
 * coordinate axes. Order of measurement is angular velocity around the x, y,
 * and z axis of the entity. The positive direction is determined by the right
 * hand rule. Section 6.2.7
 */
public class AngularVelocityVectorTest {

	@Test
	public void testAngularVelocityVector() {
	}
}