// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Angular velocity measured in radians per second out each of the entity's own coordinate axes. Order of measurement is angular velocity around the x, y, and z axis of the entity. The positive direction is determined by the right hand rule. Section 6.2.7
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Angular velocity measured in radians per second out each of the entity's own coordinate axes. Order of measurement is angular velocity around the x, y, and z axis of the entity. The positive direction is determined by the right hand rule. Section 6.2.7 */
public class AngularVelocityVectorTest {
  public AngularVelocityVectorTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.AngularVelocityVector openDis = new edu.nps.moves.dis7.AngularVelocityVector();
    com.phyzicsz.dis7.AngularVelocityVector dis = new AngularVelocityVector();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
