// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Location of the radiating portion of the antenna, specified in world coordinates and entity coordinates. Section 6.2.8
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Location of the radiating portion of the antenna, specified in world coordinates and entity coordinates. Section 6.2.8 */
public class AntennaLocationTest {
  public AntennaLocationTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.AntennaLocation openDis = new edu.nps.moves.dis7.AntennaLocation();
    com.phyzicsz.dis7.AntennaLocation dis = new AntennaLocation();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
