/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Location of the radiating portion of the antenna, specified in world
 * coordinates and entity coordinates. Section 6.2.8
 */
public class AntennaLocationTest {

	@Test
	public void testAntennaLocation() {
	}
}