// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Information about the addition/modification of an oobject that is geometrically anchored to the terrain with a set of three or more points that come to a closure. Section 7.10.6 COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Information about the addition/modification of an oobject that is geometrically anchored to the terrain with a set of three or more points that come to a closure. Section 7.10.6 COMPLETE */
public class ArealObjectStatePduTest {
  public ArealObjectStatePduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.ArealObjectStatePdu openDis = new edu.nps.moves.dis7.ArealObjectStatePdu();
    com.phyzicsz.dis7.ArealObjectStatePdu dis = new ArealObjectStatePdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
