/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Information about the addition/modification of an oobject that is
 * geometrically anchored to the terrain with a set of three or more points that
 * come to a closure. Section 7.10.6 COMPLETE
 */
public class ArealObjectStatePduTest {

	@Test
	public void testArealObjectStatePdu() {
	}
}