/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * articulated parts for movable parts and a combination of moveable/attached
 * parts of an entity. Section 6.2.94.2
 */
public class ArticulatedPartsTest {

	@Test
	public void testArticulatedParts() {
	}
}