/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * An entity's associations with other entities and/or locations. For each
 * association, this record shall specify the type of the association, the
 * associated entity's EntityID and/or the associated location's world
 * coordinates. This record may be used (optionally) in a transfer transaction
 * to send internal state data from the divesting simulation to the acquiring
 * simulation (see 5.9.4). This record may also be used for other purposes.
 * Section 6.2.9
 */
public class AssociationTest {

	@Test
	public void testAssociation() {
	}
}