/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Removable parts that may be attached to an entity. Section 6.2.93.3
 */
public class AttachedPartsTest {

	@Test
	public void testAttachedParts() {
	}
}