/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Used to convey information for one or more attributes. Attributes conform to
 * the standard variable record format of 6.2.82. Section 6.2.10. NOT COMPLETE
 */
public class AttributeTest {

	@Test
	public void testAttribute() {
	}
}