/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Information about individual attributes for a particular entity, other
 * object, or event may be communicated using an Attribute PDU. The Attribute
 * PDU shall not be used to exchange data available in any other PDU except
 * where explicitly mentioned in the PDU issuance instructions within this
 * standard. See 5.3.6 for the information requirements and issuance and receipt
 * rules for this PDU. Section 7.2.6. INCOMPLETE
 */
public class AttributePduTest {

	@Test
	public void testAttributePdu() {
	}
}