// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Information related to the status of a beam. This is contained in the beam status field of the electromagnitec emission PDU. The first bit determines whether the beam is active (0) or deactivated (1). Section 6.2.12.
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Information related to the status of a beam. This is contained in the beam status field of the electromagnitec emission PDU. The first bit determines whether the beam is active (0) or deactivated (1). Section 6.2.12. */
public class BeamStatusTest {
  public BeamStatusTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.BeamStatus openDis = new edu.nps.moves.dis7.BeamStatus();
    com.phyzicsz.dis7.BeamStatus dis = new BeamStatus();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
