// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Used when the antenna pattern type field has a value of 1. Specifies the direction, pattern, and polarization of radiation from an antenna. Section 6.2.9.2
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Used when the antenna pattern type field has a value of 1. Specifies the direction, pattern, and polarization of radiation from an antenna. Section 6.2.9.2 */
public class BeamAntennaPatternTest {
  public BeamAntennaPatternTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.BeamAntennaPattern openDis = new edu.nps.moves.dis7.BeamAntennaPattern();
    com.phyzicsz.dis7.BeamAntennaPattern dis = new BeamAntennaPattern();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
