/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Describes the scan volue of an emitter beam. Section 6.2.11.
 */
public class BeamDataTest {

	@Test
	public void testBeamData() {
	}
}