// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Describes the scan volue of an emitter beam. Section 6.2.11.
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Describes the scan volue of an emitter beam. Section 6.2.11. */
public class BeamDataTest {
  public BeamDataTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.BeamData openDis = new edu.nps.moves.dis7.BeamData();
    com.phyzicsz.dis7.BeamData dis = new BeamData();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
