/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Used when the antenna pattern type field has a value of 1. Specifies the
 * direction, pattern, and polarization of radiation from an antenna. Section
 * 6.2.9.2
 */
public class BeamAntennaPatternTest {

	@Test
	public void testBeamAntennaPattern() {
	}
}