/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Information related to the status of a beam. This is contained in the beam
 * status field of the electromagnitec emission PDU. The first bit determines
 * whether the beam is active (0) or deactivated (1). Section 6.2.12.
 */
public class BeamStatusTest {

	@Test
	public void testBeamStatus() {
	}
}