// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// The Blanking Sector attribute record may be used to convey persistent areas within a scan volume where emitter power for a specific active emitter beam is reduced to an insignificant value. Section 6.2.21.2
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * The Blanking Sector attribute record may be used to convey persistent areas within a scan volume where emitter power for a specific active emitter beam is reduced to an insignificant value. Section 6.2.21.2 */
public class BlankingSectorTest {
  public BlankingSectorTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.BlankingSector openDis = new edu.nps.moves.dis7.BlankingSector();
    com.phyzicsz.dis7.BlankingSector dis = new BlankingSector();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
