/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * The Blanking Sector attribute record may be used to convey persistent areas
 * within a scan volume where emitter power for a specific active emitter beam
 * is reduced to an insignificant value. Section 6.2.21.2
 */
public class BlankingSectorTest {

	@Test
	public void testBlankingSector() {
	}
}