/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * This is wrong and breaks serialization. See section 6.2.13 aka B.2.41
 */
public class ChangeOptionsTest {

	@Test
	public void testChangeOptions() {
	}
}