/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Time measurements that exceed one hour are represented by this record. The
 * first field is the hours since the unix epoch (Jan 1 1970, used by most Unix
 * systems and java) and the second field the timestamp units since the top of
 * the hour. Section 6.2.14
 */
public class ClockTimeTest {

	@Test
	public void testClockTime() {
	}
}