/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Information about elastic collisions in a DIS exercise shall be communicated
 * using a Collision-Elastic PDU. Section 7.2.4. COMPLETE
 */
public class CollisionElasticPduTest {

	@Test
	public void testCollisionElasticPdu() {
	}
}