/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 7.2.3 Collisions between entities shall be communicated by issuing a
 * Collision PDU. COMPLETE
 */
public class CollisionPduTest {

	@Test
	public void testCollisionPdu() {
	}
}