// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Identity of a communications node. Section 6.2.48.4
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Identity of a communications node. Section 6.2.48.4 */
public class CommunicationsNodeIDTest {
  public CommunicationsNodeIDTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.CommunicationsNodeID openDis = new edu.nps.moves.dis7.CommunicationsNodeID();
    com.phyzicsz.dis7.CommunicationsNodeID dis = new CommunicationsNodeID();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
