/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Identity of a communications node. Section 6.2.48.4
 */
public class CommunicationsNodeIDTest {

	@Test
	public void testCommunicationsNodeID() {
	}
}