// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
//  Arbitrary messages can be entered into the data stream via use of this PDU. Section 7.5.13 COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 *  Arbitrary messages can be entered into the data stream via use of this PDU. Section 7.5.13 COMPLETE */
public class CommentPduTest {
  public CommentPduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.CommentPdu openDis = new edu.nps.moves.dis7.CommentPdu();
    com.phyzicsz.dis7.CommentPdu dis = new CommentPdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
