/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 5.3.12.12: Arbitrary messages. Only reliable this time. Neds manual
 * intervention to fix padding in variable datums. UNFINISHED
 */
public class CommentReliablePduTest {

	@Test
	public void testCommentReliablePdu() {
	}
}