/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Arbitrary messages can be entered into the data stream via use of this PDU.
 * Section 7.5.13 COMPLETE
 */
public class CommentPduTest {

	@Test
	public void testCommentPdu() {
	}
}