/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 7.5.2. Create a new entity. COMPLETE
 */
public class CreateEntityPduTest {

	@Test
	public void testCreateEntityPdu() {
	}
}