// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Section 5.3.12.1: creation of an entity , reliable. COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Section 5.3.12.1: creation of an entity , reliable. COMPLETE */
public class CreateEntityReliablePduTest {
  public CreateEntityReliablePduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.CreateEntityReliablePdu openDis = new edu.nps.moves.dis7.CreateEntityReliablePdu();
    com.phyzicsz.dis7.CreateEntityReliablePdu dis = new CreateEntityReliablePdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
