/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 5.3.12.1: creation of an entity , reliable. COMPLETE
 */
public class CreateEntityReliablePduTest {

	@Test
	public void testCreateEntityReliablePdu() {
	}
}