// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Section 7.5.2. Create a new entity. COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Section 7.5.2. Create a new entity. COMPLETE */
public class CreateEntityPduTest {
  public CreateEntityPduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.CreateEntityPdu openDis = new edu.nps.moves.dis7.CreateEntityPdu();
    com.phyzicsz.dis7.CreateEntityPdu dis = new CreateEntityPdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
