// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Section 7.5.9. Request for data from an entity. COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Section 7.5.9. Request for data from an entity. COMPLETE */
public class DataQueryPduTest {
  public DataQueryPduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.DataQueryPdu openDis = new edu.nps.moves.dis7.DataQueryPdu();
    com.phyzicsz.dis7.DataQueryPdu dis = new DataQueryPdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
