/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 7.5.9. Request for data from an entity. COMPLETE
 */
public class DataQueryPduTest {

	@Test
	public void testDataQueryPdu() {
	}
}