/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Information issued in response to a data query pdu or a set data pdu is
 * communicated using a data pdu. Section 7.5.11 COMPLETE
 */
public class DataPduTest {

	@Test
	public void testDataPdu() {
	}
}