/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 5.3.12.10: issued in response to a data query R or set dataR pdu.
 * Needs manual intervention to fix padding on variable datums. UNFINSIHED
 */
public class DataReliablePduTest {

	@Test
	public void testDataReliablePdu() {
	}
}