// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
//  Information issued in response to a data query pdu or a set data pdu is communicated using a data pdu. Section 7.5.11 COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 *  Information issued in response to a data query pdu or a set data pdu is communicated using a data pdu. Section 7.5.11 COMPLETE */
public class DataPduTest {
  public DataPduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.DataPdu openDis = new edu.nps.moves.dis7.DataPdu();
    com.phyzicsz.dis7.DataPdu dis = new DataPdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
