/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 5.3.12.8: request for data from an entity. COMPLETE
 */
public class DataQueryReliablePduTest {

	@Test
	public void testDataQueryReliablePdu() {
	}
}