/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * List of fixed and variable datum ID records. Section 6.2.17
 */
public class DataQueryDatumSpecificationTest {

	@Test
	public void testDataQueryDatumSpecification() {
	}
}