/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * List of fixed and variable datum records. Section 6.2.18
 */
public class DatumSpecificationTest {

	@Test
	public void testDatumSpecification() {
	}
}