// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// List of fixed and variable datum records. Section 6.2.18 
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * List of fixed and variable datum records. Section 6.2.18  */
public class DatumSpecificationTest {
  public DatumSpecificationTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.DatumSpecification openDis = new edu.nps.moves.dis7.DatumSpecification();
    com.phyzicsz.dis7.DatumSpecification dis = new DatumSpecification();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
