/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Not specified in the standard. This is used by the ESPDU
 */
public class DeadReckoningParametersTest {

	@Test
	public void testDeadReckoningParameters() {
	}
}