// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Section 5.3.7.2. Handles designating operations. COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Section 5.3.7.2. Handles designating operations. COMPLETE */
public class DesignatorPduTest {
  public DesignatorPduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.DesignatorPdu openDis = new edu.nps.moves.dis7.DesignatorPdu();
    com.phyzicsz.dis7.DesignatorPdu dis = new DesignatorPdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
