/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 5.3.7.2. Handles designating operations. COMPLETE
 */
public class DesignatorPduTest {

	@Test
	public void testDesignatorPdu() {
	}
}