/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Detonation or impact of munitions, as well as, non-munition explosions, the
 * burst or initial bloom of chaff, and the ignition of a flare shall be
 * indicated. Section 7.3.3 COMPLETE
 */
public class DetonationPduTest {

	@Test
	public void testDetonationPdu() {
	}
}