// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Firing of a directed energy weapon shall be communicated by issuing a Directed Energy Fire PDU Section 7.3.4  COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Firing of a directed energy weapon shall be communicated by issuing a Directed Energy Fire PDU Section 7.3.4  COMPLETE */
public class DirectedEnergyFirePduTest {
  public DirectedEnergyFirePduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.DirectedEnergyFirePdu openDis = new edu.nps.moves.dis7.DirectedEnergyFirePdu();
    com.phyzicsz.dis7.DirectedEnergyFirePdu dis = new DirectedEnergyFirePdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
