/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * DE Precision Aimpoint Record. Section 6.2.20.3
 */
public class DirectedEnergyPrecisionAimpointTest {

	@Test
	public void testDirectedEnergyPrecisionAimpoint() {
	}
}