/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Firing of a directed energy weapon shall be communicated by issuing a
 * Directed Energy Fire PDU Section 7.3.4 COMPLETE
 */
public class DirectedEnergyFirePduTest {

	@Test
	public void testDirectedEnergyFirePdu() {
	}
}