// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// DE energy depostion properties for a target entity. Section 6.2.20.4
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * DE energy depostion properties for a target entity. Section 6.2.20.4 */
public class DirectedEnergyTargetEnergyDepositionTest {
  public DirectedEnergyTargetEnergyDepositionTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.DirectedEnergyTargetEnergyDeposition openDis = new edu.nps.moves.dis7.DirectedEnergyTargetEnergyDeposition();
    com.phyzicsz.dis7.DirectedEnergyTargetEnergyDeposition dis = new DirectedEnergyTargetEnergyDeposition();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
