// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// DE Precision Aimpoint Record. NOT COMPLETE. Section 6.2.20.2
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * DE Precision Aimpoint Record. NOT COMPLETE. Section 6.2.20.2 */
public class DirectedEnergyAreaAimpointTest {
  public DirectedEnergyAreaAimpointTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.DirectedEnergyAreaAimpoint openDis = new edu.nps.moves.dis7.DirectedEnergyAreaAimpoint();
    com.phyzicsz.dis7.DirectedEnergyAreaAimpoint dis = new DirectedEnergyAreaAimpoint();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
