/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Damage sustained by an entity due to directed energy. Location of the damage
 * based on a relative x,y,z location from the center of the entity. Section
 * 6.2.15.2
 */
public class DirectedEnergyDamageTest {

	@Test
	public void testDirectedEnergyDamage() {
	}
}