// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Damage sustained by an entity due to directed energy. Location of the damage based on a relative x,y,z location from the center of the entity. Section 6.2.15.2
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Damage sustained by an entity due to directed energy. Location of the damage based on a relative x,y,z location from the center of the entity. Section 6.2.15.2 */
public class DirectedEnergyDamageTest {
  public DirectedEnergyDamageTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.DirectedEnergyDamage openDis = new edu.nps.moves.dis7.DirectedEnergyDamage();
    com.phyzicsz.dis7.DirectedEnergyDamage dis = new DirectedEnergyDamage();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
