/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * DE energy depostion properties for a target entity. Section 6.2.20.4
 */
public class DirectedEnergyTargetEnergyDepositionTest {

	@Test
	public void testDirectedEnergyTargetEnergyDeposition() {
	}
}