/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * DE Precision Aimpoint Record. NOT COMPLETE. Section 6.2.20.2
 */
public class DirectedEnergyAreaAimpointTest {

	@Test
	public void testDirectedEnergyAreaAimpoint() {
	}
}