// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Section 5.3.7. Electronic Emissions. Abstract superclass for distirubted emissions PDU
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Section 5.3.7. Electronic Emissions. Abstract superclass for distirubted emissions PDU */
public class DistributedEmissionsFamilyPduTest {
  public DistributedEmissionsFamilyPduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.DistributedEmissionsFamilyPdu openDis = new edu.nps.moves.dis7.DistributedEmissionsFamilyPdu();
    com.phyzicsz.dis7.DistributedEmissionsFamilyPdu dis = new DistributedEmissionsFamilyPdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
