/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 5.3.7. Electronic Emissions. Abstract superclass for distirubted
 * emissions PDU
 */
public class DistributedEmissionsFamilyPduTest {

	@Test
	public void testDistributedEmissionsFamilyPdu() {
	}
}