/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Contains electromagnetic emmission regeneration parameters that are variable
 * throught a scenario. Section 6.2.22.
 */
public class EEFundamentalParameterDataTest {

	@Test
	public void testEEFundamentalParameterData() {
	}
}