// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Contains electromagnetic emmission regeneration parameters that are variable throught a scenario. Section 6.2.22.
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Contains electromagnetic emmission regeneration parameters that are variable throught a scenario. Section 6.2.22. */
public class EEFundamentalParameterDataTest {
  public EEFundamentalParameterDataTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.EEFundamentalParameterData openDis = new edu.nps.moves.dis7.EEFundamentalParameterData();
    com.phyzicsz.dis7.EEFundamentalParameterData dis = new EEFundamentalParameterData();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
