/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * 64 bit piece of data
 */
public class EightByteChunkTest {

	@Test
	public void testEightByteChunk() {
	}
}