// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// 64 bit piece of data
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * 64 bit piece of data */
public class EightByteChunkTest {
  public EightByteChunkTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.EightByteChunk openDis = new edu.nps.moves.dis7.EightByteChunk();
    com.phyzicsz.dis7.EightByteChunk dis = new EightByteChunk();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
