/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 5.3.7.1. Information about active electronic warfare (EW) emissions
 * and active EW countermeasures shall be communicated using an Electromagnetic
 * Emission PDU. NOT COMPLETE
 */
public class ElectronicEmissionsPduTest {

	@Test
	public void testElectronicEmissionsPdu() {
	}
}