// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Section 5.3.7.1. Information about active electronic warfare (EW) emissions and active EW countermeasures shall be communicated using an Electromagnetic Emission PDU. NOT COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Section 5.3.7.1. Information about active electronic warfare (EW) emissions and active EW countermeasures shall be communicated using an Electromagnetic Emission PDU. NOT COMPLETE */
public class ElectronicEmissionsPduTest {
  public ElectronicEmissionsPduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.ElectronicEmissionsPdu openDis = new edu.nps.moves.dis7.ElectronicEmissionsPdu();
    com.phyzicsz.dis7.ElectronicEmissionsPdu dis = new ElectronicEmissionsPdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
