/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * This field shall specify information about a particular emitter system.
 * Section 6.2.23.
 */
public class EmitterSystemTest {

	@Test
	public void testEmitterSystem() {
	}
}