// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// This field shall specify information about a particular emitter system. Section 6.2.23.
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * This field shall specify information about a particular emitter system. Section 6.2.23. */
public class EmitterSystemTest {
  public EmitterSystemTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.EmitterSystem openDis = new edu.nps.moves.dis7.EmitterSystem();
    com.phyzicsz.dis7.EmitterSystem dis = new EmitterSystem();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
