// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// For each type or location of engine fuell, this record specifies the type, location, fuel measurement units, and reload quantity and maximum quantity. Section 6.2.25.
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * For each type or location of engine fuell, this record specifies the type, location, fuel measurement units, and reload quantity and maximum quantity. Section 6.2.25. */
public class EngineFuelReloadTest {
  public EngineFuelReloadTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.EngineFuelReload openDis = new edu.nps.moves.dis7.EngineFuelReload();
    com.phyzicsz.dis7.EngineFuelReload dis = new EngineFuelReload();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
