/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * For each type or location of engine fuell, this record specifies the type,
 * location, fuel measurement units, and reload quantity and maximum quantity.
 * Section 6.2.25.
 */
public class EngineFuelReloadTest {

	@Test
	public void testEngineFuelReload() {
	}
}