// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Information about an entity's engine fuel. Section 6.2.24.
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Information about an entity's engine fuel. Section 6.2.24. */
public class EngineFuelTest {
  public EngineFuelTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.EngineFuel openDis = new edu.nps.moves.dis7.EngineFuel();
    com.phyzicsz.dis7.EngineFuel dis = new EngineFuel();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
