/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Association or disassociation of two entities. Section 6.2.94.4.3
 */
public class EntityAssociationTest {

	@Test
	public void testEntityAssociation() {
	}
}