/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Specifies the character set used inthe first byte, followed by 11 characters
 * of text data. Section 6.29
 */
public class EntityMarkingTest {

	@Test
	public void testEntityMarking() {
	}
}