/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Association or disassociation of two entities. Section 6.2.94.5
 */
public class EntityTypeVPTest {

	@Test
	public void testEntityTypeVP() {
	}
}