// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
//  Managment of grouping of PDUs, and more. Section 7.8
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 *  Managment of grouping of PDUs, and more. Section 7.8 */
public class EntityManagementFamilyPduTest {
  public EntityManagementFamilyPduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.EntityManagementFamilyPdu openDis = new edu.nps.moves.dis7.EntityManagementFamilyPdu();
    com.phyzicsz.dis7.EntityManagementFamilyPdu dis = new EntityManagementFamilyPdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
