// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Specifies the character set used inthe first byte, followed by 11 characters of text data. Section 6.29
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Specifies the character set used inthe first byte, followed by 11 characters of text data. Section 6.29 */
public class EntityMarkingTest {
  public EntityMarkingTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.EntityMarking openDis = new edu.nps.moves.dis7.EntityMarking();
    com.phyzicsz.dis7.EntityMarking dis = new EntityMarking();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
