/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 5.3.3. Common superclass for EntityState, Collision,
 * collision-elastic, and entity state update PDUs. This should be abstract.
 * COMPLETE
 */
public class EntityInformationFamilyPduTest {

	@Test
	public void testEntityInformationFamilyPdu() {
	}
}