/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * shall be used to communicate detailed damage information sustained by an
 * entity regardless of the source of the damage Section 7.3.5 COMPLETE
 */
public class EntityDamageStatusPduTest {

	@Test
	public void testEntityDamageStatusPdu() {
	}
}