/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Identifies the type of Entity
 */
public class EntityTypeTest {

	@Test
	public void testEntityType() {
	}
}