/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Nonstatic information about a particular entity may be communicated by
 * issuing an Entity State Update PDU. Section 7.2.5. COMPLETE
 */
public class EntityStateUpdatePduTest {

	@Test
	public void testEntityStateUpdatePdu() {
	}
}