/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * more laconically named EntityIdentifier
 */
public class EntityIDTest {

	@Test
	public void testEntityID() {
	}
}