// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Represents the postion and state of one entity in the world. Section 7.2.2. COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Represents the postion and state of one entity in the world. Section 7.2.2. COMPLETE */
public class EntityStatePduTest {
  public EntityStatePduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.EntityStatePdu openDis = new edu.nps.moves.dis7.EntityStatePdu();
    com.phyzicsz.dis7.EntityStatePdu dis = new EntityStatePdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
