/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Managment of grouping of PDUs, and more. Section 7.8
 */
public class EntityManagementFamilyPduTest {

	@Test
	public void testEntityManagementFamilyPdu() {
	}
}