/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Entity Identifier. Unique ID for entities in the world. Consists of an
 * simulation address and a entity number. Section 6.2.28.
 */
public class EntityIdentifierTest {

	@Test
	public void testEntityIdentifier() {
	}
}