/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Represents the postion and state of one entity in the world. Section 7.2.2.
 * COMPLETE
 */
public class EntityStatePduTest {

	@Test
	public void testEntityStatePdu() {
	}
}