/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Information about a geometry, a state associated with a geometry, a bounding
 * volume, or an associated entity ID. NOTE: this class requires hand coding.
 * 6.2.31
 */
public class EnvironmentGeneralTest {

	@Test
	public void testEnvironmentGeneral() {
	}
}