// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Incomplete environment record; requires hand coding to fix. Section 6.2.31.1
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Incomplete environment record; requires hand coding to fix. Section 6.2.31.1 */
public class EnvironmentTest {
  public EnvironmentTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.Environment openDis = new edu.nps.moves.dis7.Environment();
    com.phyzicsz.dis7.Environment dis = new Environment();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
