/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Description of environmental data in environmental process and gridded data
 * PDUs. Section 6.2.32
 */
public class EnvironmentTypeTest {

	@Test
	public void testEnvironmentType() {
	}
}