// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Description of environmental data in environmental process and gridded data PDUs. Section 6.2.32
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Description of environmental data in environmental process and gridded data PDUs. Section 6.2.32 */
public class EnvironmentTypeTest {
  public EnvironmentTypeTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.EnvironmentType openDis = new edu.nps.moves.dis7.EnvironmentType();
    com.phyzicsz.dis7.EnvironmentType dis = new EnvironmentType();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
