/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Incomplete environment record; requires hand coding to fix. Section 6.2.31.1
 */
public class EnvironmentTest {

	@Test
	public void testEnvironment() {
	}
}