// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
//  Information about a geometry, a state associated with a geometry, a bounding volume, or an associated entity ID. NOTE: this class requires hand coding. 6.2.31
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 *  Information about a geometry, a state associated with a geometry, a bounding volume, or an associated entity ID. NOTE: this class requires hand coding. 6.2.31 */
public class EnvironmentGeneralTest {
  public EnvironmentGeneralTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.EnvironmentGeneral openDis = new edu.nps.moves.dis7.EnvironmentGeneral();
    com.phyzicsz.dis7.EnvironmentGeneral dis = new EnvironmentGeneral();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
