/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Three floating point values representing an orientation, psi, theta, and phi,
 * aka the euler angles, in radians. Section 6.2.33
 */
public class EulerAnglesTest {

	@Test
	public void testEulerAngles() {
	}
}