// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Three floating point values representing an orientation, psi, theta, and phi, aka the euler angles, in radians. Section 6.2.33
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Three floating point values representing an orientation, psi, theta, and phi, aka the euler angles, in radians. Section 6.2.33 */
public class EulerAnglesTest {
  public EulerAnglesTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.EulerAngles openDis = new edu.nps.moves.dis7.EulerAngles();
    com.phyzicsz.dis7.EulerAngles dis = new EulerAngles();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
