/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Reports occurance of a significant event to the simulation manager. Section
 * 7.5.12. COMPLETE
 */
public class EventReportPduTest {

	@Test
	public void testEventReportPdu() {
	}
}