/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 5.3.12.11: reports the occurance of a significatnt event to the
 * simulation manager. Needs manual intervention to fix padding in variable
 * datums. UNFINISHED.
 */
public class EventReportReliablePduTest {

	@Test
	public void testEventReportReliablePdu() {
	}
}