// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
//  Reports occurance of a significant event to the simulation manager. Section 7.5.12. COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 *  Reports occurance of a significant event to the simulation manager. Section 7.5.12. COMPLETE */
public class EventReportPduTest {
  public EventReportPduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.EventReportPdu openDis = new edu.nps.moves.dis7.EventReportPdu();
    com.phyzicsz.dis7.EventReportPdu dis = new EventReportPdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
