// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Identifies an event in the world. Use this format for ONLY the LiveEntityPdu. Section 6.2.34.
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Identifies an event in the world. Use this format for ONLY the LiveEntityPdu. Section 6.2.34. */
public class EventIdentifierLiveEntityTest {
  public EventIdentifierLiveEntityTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.EventIdentifierLiveEntity openDis = new edu.nps.moves.dis7.EventIdentifierLiveEntity();
    com.phyzicsz.dis7.EventIdentifierLiveEntity dis = new EventIdentifierLiveEntity();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
