/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Identifies an event in the world. Use this format for every PDU EXCEPT the
 * LiveEntityPdu. Section 6.2.34.
 */
public class EventIdentifierTest {

	@Test
	public void testEventIdentifier() {
	}
}