/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * An entity's expendable (chaff, flares, etc) information. Section 6.2.37
 */
public class ExpendableReloadTest {

	@Test
	public void testExpendableReload() {
	}
}