// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// An entity's expendable (chaff, flares, etc) information. Section 6.2.37
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * An entity's expendable (chaff, flares, etc) information. Section 6.2.37 */
public class ExpendableReloadTest {
  public ExpendableReloadTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.ExpendableReload openDis = new edu.nps.moves.dis7.ExpendableReload();
    com.phyzicsz.dis7.ExpendableReload dis = new ExpendableReload();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
