/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Burst of chaff or expendible device. Section 6.2.19.4
 */
public class ExpendableDescriptorTest {

	@Test
	public void testExpendableDescriptor() {
	}
}