// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Burst of chaff or expendible device. Section 6.2.19.4
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Burst of chaff or expendible device. Section 6.2.19.4 */
public class ExpendableDescriptorTest {
  public ExpendableDescriptorTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.ExpendableDescriptor openDis = new edu.nps.moves.dis7.ExpendableDescriptor();
    com.phyzicsz.dis7.ExpendableDescriptor dis = new ExpendableDescriptor();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
