// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Explosion of a non-munition. Section 6.2.19.3
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Explosion of a non-munition. Section 6.2.19.3 */
public class ExplosionDescriptorTest {
  public ExplosionDescriptorTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.ExplosionDescriptor openDis = new edu.nps.moves.dis7.ExplosionDescriptor();
    com.phyzicsz.dis7.ExplosionDescriptor dis = new ExplosionDescriptor();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
