/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Explosion of a non-munition. Section 6.2.19.3
 */
public class ExplosionDescriptorTest {

	@Test
	public void testExplosionDescriptor() {
	}
}