/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * The False Targets attribute record shall be used to communicate discrete
 * values that are associated with false targets jamming that cannot be
 * referenced to an emitter mode. The values provided in the False Targets
 * attri- bute record shall be considered valid only for the victim radar beams
 * listed in the jamming beam's Track/Jam Data records (provided in the
 * associated Electromagnetic Emission PDU). Section 6.2.21.3
 */
public class FalseTargetsAttributeTest {

	@Test
	public void testFalseTargetsAttribute() {
	}
}