// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Represents the postion and state of one entity in the world. This is identical in function to entity state pdu, but generates less garbage to collect in the Java world. Section 7.2.2. COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Represents the postion and state of one entity in the world. This is identical in function to entity state pdu, but generates less garbage to collect in the Java world. Section 7.2.2. COMPLETE */
public class FastEntityStatePduTest {
  public FastEntityStatePduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.FastEntityStatePdu openDis = new edu.nps.moves.dis7.FastEntityStatePdu();
    com.phyzicsz.dis7.FastEntityStatePdu dis = new FastEntityStatePdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
