/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Represents the postion and state of one entity in the world. This is
 * identical in function to entity state pdu, but generates less garbage to
 * collect in the Java world. Section 7.2.2. COMPLETE
 */
public class FastEntityStatePduTest {

	@Test
	public void testFastEntityStatePdu() {
	}
}