/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * The firing of a weapon or expendable shall be communicated by issuing a Fire
 * PDU. Sectioin 7.3.2. COMPLETE
 */
public class FirePduTest {

	@Test
	public void testFirePdu() {
	}
}