// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
//  The firing of a weapon or expendable shall be communicated by issuing a Fire PDU. Sectioin 7.3.2. COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 *  The firing of a weapon or expendable shall be communicated by issuing a Fire PDU. Sectioin 7.3.2. COMPLETE */
public class FirePduTest {
  public FirePduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.FirePdu openDis = new edu.nps.moves.dis7.FirePdu();
    com.phyzicsz.dis7.FirePdu dis = new FirePdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
