/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Fixed Datum Record. Section 6.2.38
 */
public class FixedDatumTest {

	@Test
	public void testFixedDatum() {
	}
}