// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Fixed Datum Record. Section 6.2.38
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Fixed Datum Record. Section 6.2.38 */
public class FixedDatumTest {
  public FixedDatumTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.FixedDatum openDis = new edu.nps.moves.dis7.FixedDatum();
    com.phyzicsz.dis7.FixedDatum dis = new FixedDatum();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
