/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * 32 bit piece of data
 */
public class FourByteChunkTest {

	@Test
	public void testFourByteChunk() {
	}
}