// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// 32 bit piece of data
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * 32 bit piece of data */
public class FourByteChunkTest {
  public FourByteChunkTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.FourByteChunk openDis = new edu.nps.moves.dis7.FourByteChunk();
    com.phyzicsz.dis7.FourByteChunk dis = new FourByteChunk();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
