/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Basic operational data for IFF. Section 6.2.40.
 */
public class FundamentalOperationalDataTest {

	@Test
	public void testFundamentalOperationalData() {
	}
}