/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Grid axis record for fixed data. Section 6.2.41
 */
public class GridAxisTest {

	@Test
	public void testGridAxis() {
	}
}