/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Grid axis descriptor fo variable spacing axis data. NOT COMPLETE. Need
 * padding to 64 bit boundary.
 */
public class GridAxisDescriptorVariableTest {

	@Test
	public void testGridAxisDescriptorVariable() {
	}
}