// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Grid axis record for fixed data. Section 6.2.41
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Grid axis record for fixed data. Section 6.2.41 */
public class GridAxisTest {
  public GridAxisTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.GridAxis openDis = new edu.nps.moves.dis7.GridAxis();
    com.phyzicsz.dis7.GridAxis dis = new GridAxis();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
