// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Unique designation of a group of entities contained in the isGroupOfPdu. Represents a group of entities rather than a single entity. Section 6.2.43
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Unique designation of a group of entities contained in the isGroupOfPdu. Represents a group of entities rather than a single entity. Section 6.2.43 */
public class GroupIDTest {
  public GroupIDTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.GroupID openDis = new edu.nps.moves.dis7.GroupID();
    com.phyzicsz.dis7.GroupID dis = new GroupID();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
