/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Unique designation of a group of entities contained in the isGroupOfPdu.
 * Represents a group of entities rather than a single entity. Section 6.2.43
 */
public class GroupIDTest {

	@Test
	public void testGroupID() {
	}
}