// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Requires hand coding to be useful. Section 6.2.43
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Requires hand coding to be useful. Section 6.2.43 */
public class IffDataSpecificationTest {
  public IffDataSpecificationTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.IffDataSpecification openDis = new edu.nps.moves.dis7.IffDataSpecification();
    com.phyzicsz.dis7.IffDataSpecification dis = new IffDataSpecification();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
