/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * repeating element if IFF Data specification record
 */
public class IFFDataTest {

	@Test
	public void testIFFData() {
	}
}