// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// repeating element if IFF Data specification record
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * repeating element if IFF Data specification record */
public class IFFDataTest {
  public IFFDataTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.IFFData openDis = new edu.nps.moves.dis7.IFFData();
    com.phyzicsz.dis7.IFFData dis = new IFFData();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
