/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Requires hand coding to be useful. Section 6.2.43
 */
public class IffDataSpecificationTest {

	@Test
	public void testIffDataSpecification() {
	}
}