/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Fundamental IFF atc data. Section 6.2.45
 */
public class IFFFundamentalParameterDataTest {

	@Test
	public void testIFFFundamentalParameterData() {
	}
}