// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Fundamental IFF atc data. Section 6.2.45
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Fundamental IFF atc data. Section 6.2.45 */
public class IFFFundamentalParameterDataTest {
  public IFFFundamentalParameterDataTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.IFFFundamentalParameterData openDis = new edu.nps.moves.dis7.IFFFundamentalParameterData();
    com.phyzicsz.dis7.IFFFundamentalParameterData dis = new IFFFundamentalParameterData();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
