// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Unique designation of an attached or unattached intercom in an event or exercirse. Section 6.2.48
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Unique designation of an attached or unattached intercom in an event or exercirse. Section 6.2.48 */
public class IntercomIdentifierTest {
  public IntercomIdentifierTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.IntercomIdentifier openDis = new edu.nps.moves.dis7.IntercomIdentifier();
    com.phyzicsz.dis7.IntercomIdentifier dis = new IntercomIdentifier();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
