/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Unique designation of an attached or unattached intercom in an event or
 * exercirse. Section 6.2.48
 */
public class IntercomIdentifierTest {

	@Test
	public void testIntercomIdentifier() {
	}
}