/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Intercom communcations parameters. Section 6.2.47. This requires hand coding
 */
public class IntercomCommunicationsParametersTest {

	@Test
	public void testIntercomCommunicationsParameters() {
	}
}