// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Intercom communcations parameters. Section 6.2.47.  This requires hand coding
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Intercom communcations parameters. Section 6.2.47.  This requires hand coding */
public class IntercomCommunicationsParametersTest {
  public IntercomCommunicationsParametersTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.IntercomCommunicationsParameters openDis = new edu.nps.moves.dis7.IntercomCommunicationsParameters();
    com.phyzicsz.dis7.IntercomCommunicationsParameters dis = new IntercomCommunicationsParameters();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
