/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Detailed inofrmation about the state of an intercom device and the actions it
 * is requestion of another intercom device, or the response to a requested
 * action. Required manual intervention to fix the intercom parameters, which
 * can be of varialbe length. Section 7.7.5 UNFINSISHED
 */
public class IntercomControlPduTest {

	@Test
	public void testIntercomControlPdu() {
	}
}