// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
//  Actual transmission of intercome voice data. Section 7.7.5. COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 *  Actual transmission of intercome voice data. Section 7.7.5. COMPLETE */
public class IntercomSignalPduTest {
  public IntercomSignalPduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.IntercomSignalPdu openDis = new edu.nps.moves.dis7.IntercomSignalPdu();
    com.phyzicsz.dis7.IntercomSignalPdu dis = new IntercomSignalPdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
