/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Actual transmission of intercome voice data. Section 7.7.5. COMPLETE
 */
public class IntercomSignalPduTest {

	@Test
	public void testIntercomSignalPdu() {
	}
}