/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * A communications node that is part of a simulted communcations network.
 * Section 6.2.49.2
 */
public class IOCommunicationsNodeTest {

	@Test
	public void testIOCommunicationsNode() {
	}
}