// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// A communications node that is part of a simulted communcations network. Section 6.2.49.2
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * A communications node that is part of a simulted communcations network. Section 6.2.49.2 */
public class IOCommunicationsNodeTest {
  public IOCommunicationsNodeTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.IOCommunicationsNode openDis = new edu.nps.moves.dis7.IOCommunicationsNode();
    com.phyzicsz.dis7.IOCommunicationsNode dis = new IOCommunicationsNode();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
