/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Effect of IO on an entity. Section 6.2.49.3
 */
public class IOEffectTest {

	@Test
	public void testIOEffect() {
	}
}