// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Effect of IO on an entity. Section 6.2.49.3
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Effect of IO on an entity. Section 6.2.49.3 */
public class IOEffectTest {
  public IOEffectTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.IOEffect openDis = new edu.nps.moves.dis7.IOEffect();
    com.phyzicsz.dis7.IOEffect dis = new IOEffect();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
