// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
//  The joining of two or more simulation entities is communicated by this PDU. Section 7.8.5 COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 *  The joining of two or more simulation entities is communicated by this PDU. Section 7.8.5 COMPLETE */
public class IsPartOfPduTest {
  public IsPartOfPduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.IsPartOfPdu openDis = new edu.nps.moves.dis7.IsPartOfPdu();
    com.phyzicsz.dis7.IsPartOfPdu dis = new IsPartOfPdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
