/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * The joining of two or more simulation entities is communicated by this PDU.
 * Section 7.8.5 COMPLETE
 */
public class IsPartOfPduTest {

	@Test
	public void testIsPartOfPdu() {
	}
}