// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Jamming technique. Section 6.2.49
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Jamming technique. Section 6.2.49 */
public class JammingTechniqueTest {
  public JammingTechniqueTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.JammingTechnique openDis = new edu.nps.moves.dis7.JammingTechnique();
    com.phyzicsz.dis7.JammingTechnique dis = new JammingTechnique();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
