/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Jamming technique. Section 6.2.49
 */
public class JammingTechniqueTest {

	@Test
	public void testJammingTechnique() {
	}
}