// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Identity of a communications node. Section 6.2.50
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Identity of a communications node. Section 6.2.50 */
public class LaunchedMunitionRecordTest {
  public LaunchedMunitionRecordTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.LaunchedMunitionRecord openDis = new edu.nps.moves.dis7.LaunchedMunitionRecord();
    com.phyzicsz.dis7.LaunchedMunitionRecord dis = new LaunchedMunitionRecord();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
