/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Identity of a communications node. Section 6.2.50
 */
public class LaunchedMunitionRecordTest {

	@Test
	public void testLaunchedMunitionRecord() {
	}
}