// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// The identification of the additional information layer number, layer-specific information, and the length of the layer. Section 6.2.51
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * The identification of the additional information layer number, layer-specific information, and the length of the layer. Section 6.2.51 */
public class LayerHeaderTest {
  public LayerHeaderTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.LayerHeader openDis = new edu.nps.moves.dis7.LayerHeader();
    com.phyzicsz.dis7.LayerHeader dis = new LayerHeader();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
