/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * The identification of the additional information layer number, layer-specific
 * information, and the length of the layer. Section 6.2.51
 */
public class LayerHeaderTest {

	@Test
	public void testLayerHeader() {
	}
}