// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// : Information abut the addition or modification of a synthecic enviroment object that      is anchored to the terrain with a single point and has size or orientation. Section 7.10.5 COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * : Information abut the addition or modification of a synthecic enviroment object that      is anchored to the terrain with a single point and has size or orientation. Section 7.10.5 COMPLETE */
public class LinearObjectStatePduTest {
  public LinearObjectStatePduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.LinearObjectStatePdu openDis = new edu.nps.moves.dis7.LinearObjectStatePdu();
    com.phyzicsz.dis7.LinearObjectStatePdu dis = new LinearObjectStatePdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
