// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// The specification of an individual segment of a linear segment synthetic environment object in a Linear Object State PDU Section 6.2.52
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * The specification of an individual segment of a linear segment synthetic environment object in a Linear Object State PDU Section 6.2.52 */
public class LinearSegmentParameterTest {
  public LinearSegmentParameterTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.LinearSegmentParameter openDis = new edu.nps.moves.dis7.LinearSegmentParameter();
    com.phyzicsz.dis7.LinearSegmentParameter dis = new LinearSegmentParameter();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
