/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * The specification of an individual segment of a linear segment synthetic
 * environment object in a Linear Object State PDU Section 6.2.52
 */
public class LinearSegmentParameterTest {

	@Test
	public void testLinearSegmentParameter() {
	}
}