/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * : Information abut the addition or modification of a synthecic enviroment
 * object that is anchored to the terrain with a single point and has size or
 * orientation. Section 7.10.5 COMPLETE
 */
public class LinearObjectStatePduTest {

	@Test
	public void testLinearObjectStatePdu() {
	}
}