// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// A simulation's designation associated with all Live Entity IDs contained in Live Entity PDUs. Section 6.2.55 
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * A simulation's designation associated with all Live Entity IDs contained in Live Entity PDUs. Section 6.2.55  */
public class LiveSimulationAddressTest {
  public LiveSimulationAddressTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.LiveSimulationAddress openDis = new edu.nps.moves.dis7.LiveSimulationAddress();
    com.phyzicsz.dis7.LiveSimulationAddress dis = new LiveSimulationAddress();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
