/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * A simulation's designation associated with all Live Entity IDs contained in
 * Live Entity PDUs. Section 6.2.55
 */
public class LiveSimulationAddressTest {

	@Test
	public void testLiveSimulationAddress() {
	}
}