/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * The live entity PDUs have a header with some different field names, but the
 * same length. Section 9.3.2
 */
public class LiveEntityPduTest {

	@Test
	public void testLiveEntityPdu() {
	}
}