/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * The unique designation of each entity in an event or exercise that is
 * contained in a Live Entity PDU. Section 6.2.54
 */
public class LiveEntityIdentifierTest {

	@Test
	public void testLiveEntityIdentifier() {
	}
}