// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// The unique designation of each entity in an event or exercise that is contained in a Live Entity PDU. Section 6.2.54 
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * The unique designation of each entity in an event or exercise that is contained in a Live Entity PDU. Section 6.2.54  */
public class LiveEntityIdentifierTest {
  public LiveEntityIdentifierTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.LiveEntityIdentifier openDis = new edu.nps.moves.dis7.LiveEntityIdentifier();
    com.phyzicsz.dis7.LiveEntityIdentifier dis = new LiveEntityIdentifier();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
