// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
//  Abstract superclass for logistics PDUs. Section 7.4 COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 *  Abstract superclass for logistics PDUs. Section 7.4 COMPLETE */
public class LogisticsFamilyPduTest {
  public LogisticsFamilyPduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.LogisticsFamilyPdu openDis = new edu.nps.moves.dis7.LogisticsFamilyPdu();
    com.phyzicsz.dis7.LogisticsFamilyPdu dis = new LogisticsFamilyPdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
