/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Abstract superclass for logistics PDUs. Section 7.4 COMPLETE
 */
public class LogisticsFamilyPduTest {

	@Test
	public void testLogisticsFamilyPdu() {
	}
}