// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// information about the complete minefield. The minefield presence, perimiter, etc. Section 7.9.2 COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * information about the complete minefield. The minefield presence, perimiter, etc. Section 7.9.2 COMPLETE */
public class MinefieldStatePduTest {
  public MinefieldStatePduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.MinefieldStatePdu openDis = new edu.nps.moves.dis7.MinefieldStatePdu();
    com.phyzicsz.dis7.MinefieldStatePdu dis = new MinefieldStatePdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
