/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * proivde the means to request a retransmit of a minefield data pdu. Section
 * 7.9.5 COMPLETE
 */
public class MinefieldResponseNackPduTest {

	@Test
	public void testMinefieldResponseNackPdu() {
	}
}