// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// The unique designation of a minefield Section 6.2.56 
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * The unique designation of a minefield Section 6.2.56  */
public class MinefieldIdentifierTest {
  public MinefieldIdentifierTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.MinefieldIdentifier openDis = new edu.nps.moves.dis7.MinefieldIdentifier();
    com.phyzicsz.dis7.MinefieldIdentifier dis = new MinefieldIdentifier();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
