/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * information about the complete minefield. The minefield presence, perimiter,
 * etc. Section 7.9.2 COMPLETE
 */
public class MinefieldStatePduTest {

	@Test
	public void testMinefieldStatePdu() {
	}
}