/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * The unique designation of a mine contained in the Minefield Data PDU. No
 * espdus are issued for mine entities. Section 6.2.55
 */
public class MineEntityIdentifierTest {

	@Test
	public void testMineEntityIdentifier() {
	}
}