// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Information about a minefield sensor. Section 6.2.57
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Information about a minefield sensor. Section 6.2.57 */
public class MinefieldSensorTypeTest {
  public MinefieldSensorTypeTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.MinefieldSensorType openDis = new edu.nps.moves.dis7.MinefieldSensorType();
    com.phyzicsz.dis7.MinefieldSensorType dis = new MinefieldSensorType();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
