// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
//  Abstract superclass for PDUs relating to minefields. Section 7.9
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 *  Abstract superclass for PDUs relating to minefields. Section 7.9 */
public class MinefieldFamilyPduTest {
  public MinefieldFamilyPduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.MinefieldFamilyPdu openDis = new edu.nps.moves.dis7.MinefieldFamilyPdu();
    com.phyzicsz.dis7.MinefieldFamilyPdu dis = new MinefieldFamilyPdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
