/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Abstract superclass for PDUs relating to minefields. Section 7.9
 */
public class MinefieldFamilyPduTest {

	@Test
	public void testMinefieldFamilyPdu() {
	}
}