// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// proivde the means to request a retransmit of a minefield data pdu. Section 7.9.5 COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * proivde the means to request a retransmit of a minefield data pdu. Section 7.9.5 COMPLETE */
public class MinefieldResponseNackPduTest {
  public MinefieldResponseNackPduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.MinefieldResponseNackPdu openDis = new edu.nps.moves.dis7.MinefieldResponseNackPdu();
    com.phyzicsz.dis7.MinefieldResponseNackPdu dis = new MinefieldResponseNackPdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
