/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * The unique designation of a minefield Section 6.2.56
 */
public class MinefieldIdentifierTest {

	@Test
	public void testMinefieldIdentifier() {
	}
}