/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Information about a minefield sensor. Section 6.2.57
 */
public class MinefieldSensorTypeTest {

	@Test
	public void testMinefieldSensorType() {
	}
}