// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Modulation parameters associated with a specific radio system. INCOMPLETE. 6.2.58 
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Modulation parameters associated with a specific radio system. INCOMPLETE. 6.2.58  */
public class ModulationParametersTest {
  public ModulationParametersTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.ModulationParameters openDis = new edu.nps.moves.dis7.ModulationParameters();
    com.phyzicsz.dis7.ModulationParameters dis = new ModulationParameters();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
