/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Information about the type of modulation used for radio transmission. 6.2.59
 */
public class ModulationTypeTest {

	@Test
	public void testModulationType() {
	}
}