/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Modulation parameters associated with a specific radio system. INCOMPLETE.
 * 6.2.58
 */
public class ModulationParametersTest {

	@Test
	public void testModulationParameters() {
	}
}