// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Information about the type of modulation used for radio transmission. 6.2.59 
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Information about the type of modulation used for radio transmission. 6.2.59  */
public class ModulationTypeTest {
  public ModulationTypeTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.ModulationType openDis = new edu.nps.moves.dis7.ModulationType();
    com.phyzicsz.dis7.ModulationType dis = new ModulationType();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
