/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Represents the firing or detonation of a munition. Section 6.2.19.2
 */
public class MunitionDescriptorTest {

	@Test
	public void testMunitionDescriptor() {
	}
}