// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// indicate weapons (munitions) previously communicated via the Munition record. Section 6.2.61 
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * indicate weapons (munitions) previously communicated via the Munition record. Section 6.2.61  */
public class MunitionReloadTest {
  public MunitionReloadTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.MunitionReload openDis = new edu.nps.moves.dis7.MunitionReload();
    com.phyzicsz.dis7.MunitionReload dis = new MunitionReload();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
