// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Represents the firing or detonation of a munition. Section 6.2.19.2
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Represents the firing or detonation of a munition. Section 6.2.19.2 */
public class MunitionDescriptorTest {
  public MunitionDescriptorTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.MunitionDescriptor openDis = new edu.nps.moves.dis7.MunitionDescriptor();
    com.phyzicsz.dis7.MunitionDescriptor dis = new MunitionDescriptor();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
