/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * An entity's munition (e.g., bomb, missile) information shall be represented
 * by one or more Munition records. For each type or location of munition, this
 * record shall specify the type, location, quantity and status of munitions
 * that an entity contains. Section 6.2.60
 */
public class MunitionTest {

	@Test
	public void testMunition() {
	}
}