/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * indicate weapons (munitions) previously communicated via the Munition record.
 * Section 6.2.61
 */
public class MunitionReloadTest {

	@Test
	public void testMunitionReload() {
	}
}