/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Information about the discrete positional relationship of the part entity
 * with respect to the its host entity Section 6.2.62
 */
public class NamedLocationIdentificationTest {

	@Test
	public void testNamedLocationIdentification() {
	}
}