// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Information about the discrete positional relationship of the part entity with respect to the its host entity Section 6.2.62 
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Information about the discrete positional relationship of the part entity with respect to the its host entity Section 6.2.62  */
public class NamedLocationIdentificationTest {
  public NamedLocationIdentificationTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.NamedLocationIdentification openDis = new edu.nps.moves.dis7.NamedLocationIdentification();
    com.phyzicsz.dis7.NamedLocationIdentification dis = new NamedLocationIdentification();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
