// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// The unique designation of an environmental object. Section 6.2.64
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * The unique designation of an environmental object. Section 6.2.64 */
public class ObjectTypeTest {
  public ObjectTypeTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.ObjectType openDis = new edu.nps.moves.dis7.ObjectType();
    com.phyzicsz.dis7.ObjectType dis = new ObjectType();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
