// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// The unique designation of an environmental object. Section 6.2.63
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * The unique designation of an environmental object. Section 6.2.63 */
public class ObjectIdentifierTest {
  public ObjectIdentifierTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.ObjectIdentifier openDis = new edu.nps.moves.dis7.ObjectIdentifier();
    com.phyzicsz.dis7.ObjectIdentifier dis = new ObjectIdentifier();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
