/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * The unique designation of an environmental object. Section 6.2.63
 */
public class ObjectIdentifierTest {

	@Test
	public void testObjectIdentifier() {
	}
}