/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * The unique designation of an environmental object. Section 6.2.64
 */
public class ObjectTypeTest {

	@Test
	public void testObjectType() {
	}
}