// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// 8 bit piece of data
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * 8 bit piece of data */
public class OneByteChunkTest {
  public OneByteChunkTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.OneByteChunk openDis = new edu.nps.moves.dis7.OneByteChunk();
    com.phyzicsz.dis7.OneByteChunk dis = new OneByteChunk();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
