/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * 8 bit piece of data
 */
public class OneByteChunkTest {

	@Test
	public void testOneByteChunk() {
	}
}