/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * used to convey entity and conflict status information associated with
 * transferring ownership of an entity. Section 6.2.65
 */
public class OwnershipStatusTest {

	@Test
	public void testOwnershipStatus() {
	}
}