// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// used to convey entity and conflict status information associated with transferring ownership of an entity. Section 6.2.65
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * used to convey entity and conflict status information associated with transferring ownership of an entity. Section 6.2.65 */
public class OwnershipStatusTest {
  public OwnershipStatusTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.OwnershipStatus openDis = new edu.nps.moves.dis7.OwnershipStatus();
    com.phyzicsz.dis7.OwnershipStatus dis = new OwnershipStatus();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
