/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Used for XML compatability. A container that holds PDUs
 */
public class PduContainerTest {

	@Test
	public void testPduContainer() {
	}
}