// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Used for XML compatability. A container that holds PDUs
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Used for XML compatability. A container that holds PDUs */
public class PduContainerTest {
  public PduContainerTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.PduContainer openDis = new edu.nps.moves.dis7.PduContainer();
    com.phyzicsz.dis7.PduContainer dis = new PduContainer();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
