/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Not used. The PDU Header Record is directly incoroporated into the PDU class.
 * Here for completness only. Section 6.2.66
 */
public class PduHeaderTest {

	@Test
	public void testPduHeader() {
	}
}