// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Not used. The PDU Header Record is directly incoroporated into the PDU class. Here for completness only. Section 6.2.66
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Not used. The PDU Header Record is directly incoroporated into the PDU class. Here for completness only. Section 6.2.66 */
public class PduHeaderTest {
  public PduHeaderTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.PduHeader openDis = new edu.nps.moves.dis7.PduHeader();
    com.phyzicsz.dis7.PduHeader dis = new PduHeader();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
