// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Non-DIS class, used on SQL databases. This is not in the DIS standard but can be helpful when saving DIS to a SQL database, particularly in Java.
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Non-DIS class, used on SQL databases. This is not in the DIS standard but can be helpful when saving DIS to a SQL database, particularly in Java. */
public class PduStreamTest {
  public PduStreamTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.PduStream openDis = new edu.nps.moves.dis7.PduStream();
    com.phyzicsz.dis7.PduStream dis = new PduStream();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
