/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Non-DIS class, used on SQL databases. This is not in the DIS standard but can
 * be helpful when saving DIS to a SQL database, particularly in Java.
 */
public class PduStreamTest {

	@Test
	public void testPduStream() {
	}
}