/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * PDU Status. These are a series of bit fields. Represented here as just a
 * byte. Section 6.2.67
 */
public class PduStatusTest {

	@Test
	public void testPduStatus() {
	}
}