/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * The superclass for all PDUs, including classic and Live Entity (LE) PDUs.
 * This incorporates the PduHeader record, section 7.2.2
 */
public class PduSuperclassTest {

	@Test
	public void testPduSuperclass() {
	}
}