// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// PDU Status. These are a series of bit fields. Represented here as just a byte. Section 6.2.67
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * PDU Status. These are a series of bit fields. Represented here as just a byte. Section 6.2.67 */
public class PduStatusTest {
  public PduStatusTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.PduStatus openDis = new edu.nps.moves.dis7.PduStatus();
    com.phyzicsz.dis7.PduStatus dis = new PduStatus();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
