// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Adds some fields to the the classic PDU
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Adds some fields to the the classic PDU */
public class PduTest {
  public PduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.Pdu openDis = new edu.nps.moves.dis7.Pdu();
    com.phyzicsz.dis7.Pdu dis = new Pdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
