/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Adds some fields to the the classic PDU
 */
public class PduTest {

	@Test
	public void testPdu() {
	}
}