// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// : Inormation abut the addition or modification of a synthecic enviroment object that is anchored to the terrain with a single point. Section 7.10.4 COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * : Inormation abut the addition or modification of a synthecic enviroment object that is anchored to the terrain with a single point. Section 7.10.4 COMPLETE */
public class PointObjectStatePduTest {
  public PointObjectStatePduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.PointObjectStatePdu openDis = new edu.nps.moves.dis7.PointObjectStatePdu();
    com.phyzicsz.dis7.PointObjectStatePdu dis = new PointObjectStatePdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
