/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * : Inormation abut the addition or modification of a synthecic enviroment
 * object that is anchored to the terrain with a single point. Section 7.10.4
 * COMPLETE
 */
public class PointObjectStatePduTest {

	@Test
	public void testPointObjectStatePdu() {
	}
}