/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * contains information describing the propulsion systems of the entity. This
 * information shall be provided for each active propulsion system defined.
 * Section 6.2.68
 */
public class PropulsionSystemDataTest {

	@Test
	public void testPropulsionSystemData() {
	}
}