// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// contains information describing the propulsion systems of the entity. This information shall be provided for each active propulsion system defined. Section 6.2.68
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * contains information describing the propulsion systems of the entity. This information shall be provided for each active propulsion system defined. Section 6.2.68 */
public class PropulsionSystemDataTest {
  public PropulsionSystemDataTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.PropulsionSystemData openDis = new edu.nps.moves.dis7.PropulsionSystemData();
    com.phyzicsz.dis7.PropulsionSystemData dis = new PropulsionSystemData();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
