// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Bit field used to identify minefield data. bits 14-15 are a 2-bit enum, other bits unused. Section 6.2.69
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Bit field used to identify minefield data. bits 14-15 are a 2-bit enum, other bits unused. Section 6.2.69 */
public class ProtocolModeTest {
  public ProtocolModeTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.ProtocolMode openDis = new edu.nps.moves.dis7.ProtocolMode();
    com.phyzicsz.dis7.ProtocolMode dis = new ProtocolMode();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
