/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Bit field used to identify minefield data. bits 14-15 are a 2-bit enum, other
 * bits unused. Section 6.2.69
 */
public class ProtocolModeTest {

	@Test
	public void testProtocolMode() {
	}
}