/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Abstract superclass for radio communications PDUs. Section 7.7
 */
public class RadioCommunicationsFamilyPduTest {

	@Test
	public void testRadioCommunicationsFamilyPdu() {
	}
}