/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * The unique designation of an attached or unattached radio in an event or
 * exercise Section 6.2.70
 */
public class RadioIdentifierTest {

	@Test
	public void testRadioIdentifier() {
	}
}