/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Identifies the type of radio. Section 6.2.71
 */
public class RadioTypeTest {

	@Test
	public void testRadioType() {
	}
}