// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// The unique designation of an attached or unattached radio in an event or exercise Section 6.2.70
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * The unique designation of an attached or unattached radio in an event or exercise Section 6.2.70 */
public class RadioIdentifierTest {
  public RadioIdentifierTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.RadioIdentifier openDis = new edu.nps.moves.dis7.RadioIdentifier();
    com.phyzicsz.dis7.RadioIdentifier dis = new RadioIdentifier();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
