// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
//  Abstract superclass for radio communications PDUs. Section 7.7
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 *  Abstract superclass for radio communications PDUs. Section 7.7 */
public class RadioCommunicationsFamilyPduTest {
  public RadioCommunicationsFamilyPduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.RadioCommunicationsFamilyPdu openDis = new edu.nps.moves.dis7.RadioCommunicationsFamilyPdu();
    com.phyzicsz.dis7.RadioCommunicationsFamilyPdu dis = new RadioCommunicationsFamilyPdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
