// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Identifies the type of radio. Section 6.2.71
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Identifies the type of radio. Section 6.2.71 */
public class RadioTypeTest {
  public RadioTypeTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.RadioType openDis = new edu.nps.moves.dis7.RadioType();
    com.phyzicsz.dis7.RadioType dis = new RadioType();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
