/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Communication of a receiver state. Section 7.7.4 COMPLETE
 */
public class ReceiverPduTest {

	@Test
	public void testReceiverPdu() {
	}
}