// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
//  Communication of a receiver state. Section 7.7.4 COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 *  Communication of a receiver state. Section 7.7.4 COMPLETE */
public class ReceiverPduTest {
  public ReceiverPduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.ReceiverPdu openDis = new edu.nps.moves.dis7.ReceiverPdu();
    com.phyzicsz.dis7.ReceiverPdu dis = new ReceiverPdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
