// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Section 5.3.12.13: A request for one or more records of data from an entity. COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Section 5.3.12.13: A request for one or more records of data from an entity. COMPLETE */
public class RecordQueryReliablePduTest {
  public RecordQueryReliablePduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.RecordQueryReliablePdu openDis = new edu.nps.moves.dis7.RecordQueryReliablePdu();
    com.phyzicsz.dis7.RecordQueryReliablePdu dis = new RecordQueryReliablePdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
