// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// The identification of the records being queried 6.2.72
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * The identification of the records being queried 6.2.72 */
public class RecordQuerySpecificationTest {
  public RecordQuerySpecificationTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.RecordQuerySpecification openDis = new edu.nps.moves.dis7.RecordQuerySpecification();
    com.phyzicsz.dis7.RecordQuerySpecification dis = new RecordQuerySpecification();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
