// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Synthetic record, made up from section 6.2.72. This is used to acheive a repeating variable list element.
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Synthetic record, made up from section 6.2.72. This is used to acheive a repeating variable list element. */
public class RecordSpecificationElementTest {
  public RecordSpecificationElementTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.RecordSpecificationElement openDis = new edu.nps.moves.dis7.RecordSpecificationElement();
    com.phyzicsz.dis7.RecordSpecificationElement dis = new RecordSpecificationElement();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
