/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 5.3.12.13: A request for one or more records of data from an entity.
 * COMPLETE
 */
public class RecordQueryReliablePduTest {

	@Test
	public void testRecordQueryReliablePdu() {
	}
}