/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Synthetic record, made up from section 6.2.72. This is used to acheive a
 * repeating variable list element.
 */
public class RecordSpecificationElementTest {

	@Test
	public void testRecordSpecificationElement() {
	}
}