/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * This record shall specify the number of record sets contained in the Record
 * Specification record and the record details. Section 6.2.73.
 */
public class RecordSpecificationTest {

	@Test
	public void testRecordSpecification() {
	}
}