/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * The identification of the records being queried 6.2.72
 */
public class RecordQuerySpecificationTest {

	@Test
	public void testRecordQuerySpecification() {
	}
}