// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// This record shall specify the number of record sets contained in the Record Specification record and the record details. Section 6.2.73.
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * This record shall specify the number of record sets contained in the Record Specification record and the record details. Section 6.2.73. */
public class RecordSpecificationTest {
  public RecordSpecificationTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.RecordSpecification openDis = new edu.nps.moves.dis7.RecordSpecification();
    com.phyzicsz.dis7.RecordSpecification dis = new RecordSpecification();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
