/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * The relationship of the part entity to its host entity. Section 6.2.74.
 */
public class RelationshipTest {

	@Test
	public void testRelationship() {
	}
}