// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// The relationship of the part entity to its host entity. Section 6.2.74.
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * The relationship of the part entity to its host entity. Section 6.2.74. */
public class RelationshipTest {
  public RelationshipTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.Relationship openDis = new edu.nps.moves.dis7.Relationship();
    com.phyzicsz.dis7.Relationship dis = new Relationship();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
