// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Section 7.5.3 The removal of an entity from an exercise shall be communicated with a Remove Entity PDU. COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Section 7.5.3 The removal of an entity from an exercise shall be communicated with a Remove Entity PDU. COMPLETE */
public class RemoveEntityPduTest {
  public RemoveEntityPduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.RemoveEntityPdu openDis = new edu.nps.moves.dis7.RemoveEntityPdu();
    com.phyzicsz.dis7.RemoveEntityPdu dis = new RemoveEntityPdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
