/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 7.5.3 The removal of an entity from an exercise shall be communicated
 * with a Remove Entity PDU. COMPLETE
 */
public class RemoveEntityPduTest {

	@Test
	public void testRemoveEntityPdu() {
	}
}