// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Section 5.3.12.2: Removal of an entity , reliable. COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Section 5.3.12.2: Removal of an entity , reliable. COMPLETE */
public class RemoveEntityReliablePduTest {
  public RemoveEntityReliablePduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.RemoveEntityReliablePdu openDis = new edu.nps.moves.dis7.RemoveEntityReliablePdu();
    com.phyzicsz.dis7.RemoveEntityReliablePdu dis = new RemoveEntityReliablePdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
