/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 5.3.12.2: Removal of an entity , reliable. COMPLETE
 */
public class RemoveEntityReliablePduTest {

	@Test
	public void testRemoveEntityReliablePdu() {
	}
}