// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// A monotonically increasing number inserted into all simulation managment PDUs. This should be a hand-coded thingie, maybe a singleton. Section 6.2.75
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * A monotonically increasing number inserted into all simulation managment PDUs. This should be a hand-coded thingie, maybe a singleton. Section 6.2.75 */
public class RequestIDTest {
  public RequestIDTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.RequestID openDis = new edu.nps.moves.dis7.RequestID();
    com.phyzicsz.dis7.RequestID dis = new RequestID();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
