/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * A monotonically increasing number inserted into all simulation managment
 * PDUs. This should be a hand-coded thingie, maybe a singleton. Section 6.2.75
 */
public class RequestIDTest {

	@Test
	public void testRequestID() {
	}
}