// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Information used to communicate the offer of supplies by a supplying entity to a receiving entity. Section 7.4.3 COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Information used to communicate the offer of supplies by a supplying entity to a receiving entity. Section 7.4.3 COMPLETE */
public class ResupplyOfferPduTest {
  public ResupplyOfferPduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.ResupplyOfferPdu openDis = new edu.nps.moves.dis7.ResupplyOfferPdu();
    com.phyzicsz.dis7.ResupplyOfferPdu dis = new ResupplyOfferPdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
