/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Information used to communicate the offer of supplies by a supplying entity
 * to a receiving entity. Section 7.4.3 COMPLETE
 */
public class ResupplyOfferPduTest {

	@Test
	public void testResupplyOfferPdu() {
	}
}