/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 7.4.4. Receipt of supplies is communicated by issuing Resupply
 * Received PDU. COMPLETE
 */
public class ResupplyReceivedPduTest {

	@Test
	public void testResupplyReceivedPdu() {
	}
}