// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Section 7.4.4. Receipt of supplies is communicated by issuing Resupply Received PDU. COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Section 7.4.4. Receipt of supplies is communicated by issuing Resupply Received PDU. COMPLETE */
public class ResupplyReceivedPduTest {
  public ResupplyReceivedPduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.ResupplyReceivedPdu openDis = new edu.nps.moves.dis7.ResupplyReceivedPdu();
    com.phyzicsz.dis7.ResupplyReceivedPdu dis = new ResupplyReceivedPdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
