/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Additional operational data for an IFF emitting system and the number of IFF
 * Fundamental Parameter Data records Section 6.2.76.
 */
public class SecondaryOperationalDataTest {

	@Test
	public void testSecondaryOperationalData() {
	}
}