// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Additional operational data for an IFF emitting system and the number of IFF Fundamental Parameter Data records Section 6.2.76.
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Additional operational data for an IFF emitting system and the number of IFF Fundamental Parameter Data records Section 6.2.76. */
public class SecondaryOperationalDataTest {
  public SecondaryOperationalDataTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.SecondaryOperationalData openDis = new edu.nps.moves.dis7.SecondaryOperationalData();
    com.phyzicsz.dis7.SecondaryOperationalData dis = new SecondaryOperationalData();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
