/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * SEES PDU, supplemental emissions entity state information. Section 7.6.6
 * COMPLETE
 */
public class SeesPduTest {

	@Test
	public void testSeesPdu() {
	}
}