/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * An entity's sensor information. Section 6.2.77.
 */
public class SensorTest {

	@Test
	public void testSensor() {
	}
}