// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// An entity's sensor information.  Section 6.2.77.
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * An entity's sensor information.  Section 6.2.77. */
public class SensorTest {
  public SensorTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.Sensor openDis = new edu.nps.moves.dis7.Sensor();
    com.phyzicsz.dis7.Sensor dis = new Sensor();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
