/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Physical separation of an entity from another entity. Section 6.2.94.6
 */
public class SeparationVPTest {

	@Test
	public void testSeparationVP() {
	}
}