/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Service Request PDU shall be used to communicate information associated with
 * one entity requesting a service from another). Section 7.4.2 COMPLETE
 */
public class ServiceRequestPduTest {

	@Test
	public void testServiceRequestPdu() {
	}
}