// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Service Request PDU shall be used to communicate information associated with                            one entity requesting a service from another). Section 7.4.2 COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Service Request PDU shall be used to communicate information associated with                            one entity requesting a service from another). Section 7.4.2 COMPLETE */
public class ServiceRequestPduTest {
  public ServiceRequestPduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.ServiceRequestPdu openDis = new edu.nps.moves.dis7.ServiceRequestPdu();
    com.phyzicsz.dis7.ServiceRequestPdu dis = new ServiceRequestPdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
