/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 5.3.12.9: initializing or chaning internal state information,
 * reliable. Needs manual intervention to fix padding on variable datums.
 * UNFINISHED
 */
public class SetDataReliablePduTest {

	@Test
	public void testSetDataReliablePdu() {
	}
}