/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 7.5.10. Change state information with the data contained in this.
 * COMPLETE
 */
public class SetDataPduTest {

	@Test
	public void testSetDataPdu() {
	}
}