/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Detailed information about a radio transmitter. This PDU requires manually
 * written code to complete. The encodingScheme field can be used in multiple
 * ways, which requires hand-written code to finish. Section 7.7.3. UNFINISHED
 */
public class SignalPduTest {

	@Test
	public void testSignalPdu() {
	}
}