/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * information abou an enitity not producing espdus. Section 6.2.79
 */
public class SilentEntitySystemTest {

	@Test
	public void testSilentEntitySystem() {
	}
}