// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// information abou an enitity not producing espdus. Section 6.2.79
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * information abou an enitity not producing espdus. Section 6.2.79 */
public class SilentEntitySystemTest {
  public SilentEntitySystemTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.SilentEntitySystem openDis = new edu.nps.moves.dis7.SilentEntitySystem();
    com.phyzicsz.dis7.SilentEntitySystem dis = new SilentEntitySystem();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
