/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 7.5 Abstract superclass for PDUs relating to the simulation itself.
 * COMPLETE
 */
public class SimulationManagementFamilyPduTest {

	@Test
	public void testSimulationManagementFamilyPdu() {
	}
}