/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * The unique designation of a simulation when using the 48-bit identifier
 * format shall be specified by the Sim- ulation Identifier record. The reason
 * that the 48-bit format is required in addition to the 32-bit simulation
 * address format that actually identifies a specific simulation is because some
 * 48-bit identifier fields in PDUs may contain either an Object Identifier,
 * such as an Entity ID, or a Simulation Identifier. Section 6.2.80
 */
public class SimulationIdentifierTest {

	@Test
	public void testSimulationIdentifier() {
	}
}