/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * A Simulation Address record shall consist of the Site Identification number
 * and the Application Identification number. Section 6.2.79
 */
public class SimulationAddressTest {

	@Test
	public void testSimulationAddress() {
	}
}