/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 5.3.12: Abstract superclass for reliable simulation management PDUs
 */
public class SimulationManagementWithReliabilityFamilyPduTest {

	@Test
	public void testSimulationManagementWithReliabilityFamilyPdu() {
	}
}