// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Section 7.5 Abstract superclass for PDUs relating to the simulation itself. COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Section 7.5 Abstract superclass for PDUs relating to the simulation itself. COMPLETE */
public class SimulationManagementFamilyPduTest {
  public SimulationManagementFamilyPduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.SimulationManagementFamilyPdu openDis = new edu.nps.moves.dis7.SimulationManagementFamilyPdu();
    com.phyzicsz.dis7.SimulationManagementFamilyPdu dis = new SimulationManagementFamilyPdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
