/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * First part of a simulation management (SIMAN) PDU and SIMAN-Reliability
 * (SIMAN-R) PDU. Sectionn 6.2.81
 */
public class SimulationManagementPduHeaderTest {

	@Test
	public void testSimulationManagementPduHeader() {
	}
}