// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// First part of a simulation management (SIMAN) PDU and SIMAN-Reliability (SIMAN-R) PDU. Sectionn 6.2.81
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * First part of a simulation management (SIMAN) PDU and SIMAN-Reliability (SIMAN-R) PDU. Sectionn 6.2.81 */
public class SimulationManagementPduHeaderTest {
  public SimulationManagementPduHeaderTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.SimulationManagementPduHeader openDis = new edu.nps.moves.dis7.SimulationManagementPduHeader();
    com.phyzicsz.dis7.SimulationManagementPduHeader dis = new SimulationManagementPduHeader();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
