/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Does not work, and causes failure in anything it is embedded in. Section
 * 6.2.83
 */
public class StandardVariableSpecificationTest {

	@Test
	public void testStandardVariableSpecification() {
	}
}