// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Does not work, and causes failure in anything it is embedded in. Section 6.2.83
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Does not work, and causes failure in anything it is embedded in. Section 6.2.83 */
public class StandardVariableSpecificationTest {
  public StandardVariableSpecificationTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.StandardVariableSpecification openDis = new edu.nps.moves.dis7.StandardVariableSpecification();
    com.phyzicsz.dis7.StandardVariableSpecification dis = new StandardVariableSpecification();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
