/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 5.3.12.3: Start resume simulation, relaible. COMPLETE
 */
public class StartResumeReliablePduTest {

	@Test
	public void testStartResumeReliablePdu() {
	}
}