// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Section 5.3.12.3: Start resume simulation, relaible. COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Section 5.3.12.3: Start resume simulation, relaible. COMPLETE */
public class StartResumeReliablePduTest {
  public StartResumeReliablePduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.StartResumeReliablePdu openDis = new edu.nps.moves.dis7.StartResumeReliablePdu();
    com.phyzicsz.dis7.StartResumeReliablePdu dis = new StartResumeReliablePdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
