// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Section 7.5.4. Start or resume an exercise. COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Section 7.5.4. Start or resume an exercise. COMPLETE */
public class StartResumePduTest {
  public StartResumePduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.StartResumePdu openDis = new edu.nps.moves.dis7.StartResumePdu();
    com.phyzicsz.dis7.StartResumePdu dis = new StartResumePdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
