/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 7.5.4. Start or resume an exercise. COMPLETE
 */
public class StartResumePduTest {

	@Test
	public void testStartResumePdu() {
	}
}