// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Section 7.5.5. Stop or freeze an enity (or exercise). COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Section 7.5.5. Stop or freeze an enity (or exercise). COMPLETE */
public class StopFreezePduTest {
  public StopFreezePduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.StopFreezePdu openDis = new edu.nps.moves.dis7.StopFreezePdu();
    com.phyzicsz.dis7.StopFreezePdu dis = new StopFreezePdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
