/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 5.3.12.4: Stop freeze simulation, relaible. COMPLETE
 */
public class StopFreezeReliablePduTest {

	@Test
	public void testStopFreezeReliablePdu() {
	}
}