/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 7.5.5. Stop or freeze an enity (or exercise). COMPLETE
 */
public class StopFreezePduTest {

	@Test
	public void testStopFreezePdu() {
	}
}