// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Information about an entity's engine fuel. Section 6.2.84.
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Information about an entity's engine fuel. Section 6.2.84. */
public class StorageFuelTest {
  public StorageFuelTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.StorageFuel openDis = new edu.nps.moves.dis7.StorageFuel();
    com.phyzicsz.dis7.StorageFuel dis = new StorageFuel();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
