/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Information about an entity's engine fuel. Section 6.2.84.
 */
public class StorageFuelTest {

	@Test
	public void testStorageFuel() {
	}
}