// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// For each type or location of Storage Fuel, this record shall specify the type, location, fuel measure- ment units, reload quantity and maximum quantity for storage fuel either for the whole entity or a specific storage fuel location (tank). Section 6.2.85.
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * For each type or location of Storage Fuel, this record shall specify the type, location, fuel measure- ment units, reload quantity and maximum quantity for storage fuel either for the whole entity or a specific storage fuel location (tank). Section 6.2.85. */
public class StorageFuelReloadTest {
  public StorageFuelReloadTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.StorageFuelReload openDis = new edu.nps.moves.dis7.StorageFuelReload();
    com.phyzicsz.dis7.StorageFuelReload dis = new StorageFuelReload();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
