/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * For each type or location of Storage Fuel, this record shall specify the
 * type, location, fuel measure- ment units, reload quantity and maximum
 * quantity for storage fuel either for the whole entity or a specific storage
 * fuel location (tank). Section 6.2.85.
 */
public class StorageFuelReloadTest {

	@Test
	public void testStorageFuelReload() {
	}
}