// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
//  A supply, and the amount of that supply. Section 6.2.86
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 *  A supply, and the amount of that supply. Section 6.2.86 */
public class SupplyQuantityTest {
  public SupplyQuantityTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.SupplyQuantity openDis = new edu.nps.moves.dis7.SupplyQuantity();
    com.phyzicsz.dis7.SupplyQuantity dis = new SupplyQuantity();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
