/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * A supply, and the amount of that supply. Section 6.2.86
 */
public class SupplyQuantityTest {

	@Test
	public void testSupplyQuantity() {
	}
}