/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Section 5.3.11: Abstract superclass for synthetic environment PDUs
 */
public class SyntheticEnvironmentFamilyPduTest {

	@Test
	public void testSyntheticEnvironmentFamilyPdu() {
	}
}