// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// The ID of the IFF emitting system. NOT COMPLETE. Section 6.2.87
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * The ID of the IFF emitting system. NOT COMPLETE. Section 6.2.87 */
public class SystemIdentifierTest {
  public SystemIdentifierTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.SystemIdentifier openDis = new edu.nps.moves.dis7.SystemIdentifier();
    com.phyzicsz.dis7.SystemIdentifier dis = new SystemIdentifier();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
