/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * The ID of the IFF emitting system. NOT COMPLETE. Section 6.2.87
 */
public class SystemIdentifierTest {

	@Test
	public void testSystemIdentifier() {
	}
}