/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * LSB is absolute or relative timestamp. Scale is 2^31 - 1 divided into one
 * hour.
 */
public class TimestampTest {

	@Test
	public void testTimestamp() {
	}
}