// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// LSB is absolute or relative timestamp. Scale is 2^31 - 1 divided into one hour.
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * LSB is absolute or relative timestamp. Scale is 2^31 - 1 divided into one hour. */
public class TimestampTest {
  public TimestampTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.Timestamp openDis = new edu.nps.moves.dis7.Timestamp();
    com.phyzicsz.dis7.Timestamp dis = new Timestamp();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
