// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Total number of record sets contained in a logical set of one or more PDUs. Used to transfer ownership, etc Section 6.2.88
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Total number of record sets contained in a logical set of one or more PDUs. Used to transfer ownership, etc Section 6.2.88 */
public class TotalRecordSetsTest {
  public TotalRecordSetsTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.TotalRecordSets openDis = new edu.nps.moves.dis7.TotalRecordSets();
    com.phyzicsz.dis7.TotalRecordSets dis = new TotalRecordSets();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
