/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Total number of record sets contained in a logical set of one or more PDUs.
 * Used to transfer ownership, etc Section 6.2.88
 */
public class TotalRecordSetsTest {

	@Test
	public void testTotalRecordSets() {
	}
}