// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
//  Track-Jam data Section 6.2.89
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 *  Track-Jam data Section 6.2.89 */
public class TrackJamDataTest {
  public TrackJamDataTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.TrackJamData openDis = new edu.nps.moves.dis7.TrackJamData();
    com.phyzicsz.dis7.TrackJamData dis = new TrackJamData();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
