/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Track-Jam data Section 6.2.89
 */
public class TrackJamDataTest {

	@Test
	public void testTrackJamData() {
	}
}