/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Detailed information about a radio transmitter. This PDU requires manually
 * written code to complete, since the modulation parameters are of variable
 * length. Section 7.7.2 UNFINISHED
 */
public class TransmitterPduTest {

	@Test
	public void testTransmitterPdu() {
	}
}