// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Detailed information about a radio transmitter. This PDU requires manually written code to complete, since the modulation parameters are of variable length. Section 7.7.2 UNFINISHED
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Detailed information about a radio transmitter. This PDU requires manually written code to complete, since the modulation parameters are of variable length. Section 7.7.2 UNFINISHED */
public class TransmitterPduTest {
  public TransmitterPduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.TransmitterPdu openDis = new edu.nps.moves.dis7.TransmitterPdu();
    com.phyzicsz.dis7.TransmitterPdu dis = new TransmitterPdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
