// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// 16 bit piece of data
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * 16 bit piece of data */
public class TwoByteChunkTest {
  public TwoByteChunkTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.TwoByteChunk openDis = new edu.nps.moves.dis7.TwoByteChunk();
    com.phyzicsz.dis7.TwoByteChunk dis = new TwoByteChunk();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
