/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * 16 bit piece of data
 */
public class TwoByteChunkTest {

	@Test
	public void testTwoByteChunk() {
	}
}