/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Regeneration parameters for active emission systems that are variable
 * throughout a scenario. Section 6.2.91
 */
public class UAFundamentalParameterTest {

	@Test
	public void testUAFundamentalParameter() {
	}
}