// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Regeneration parameters for active emission systems that are variable throughout a scenario. Section 6.2.91
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Regeneration parameters for active emission systems that are variable throughout a scenario. Section 6.2.91 */
public class UAFundamentalParameterTest {
  public UAFundamentalParameterTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.UAFundamentalParameter openDis = new edu.nps.moves.dis7.UAFundamentalParameter();
    com.phyzicsz.dis7.UAFundamentalParameter dis = new UAFundamentalParameter();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
