/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Information about underwater acoustic emmissions. This requires manual
 * cleanup. The beam data records should ALL be a the finish, rather than
 * attached to each emitter system. Section 7.6.4. UNFINISHED
 */
public class UaPduTest {

	@Test
	public void testUaPdu() {
	}
}