// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// The unique designation of one or more unattached radios in an event or exercise Section 6.2.91
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * The unique designation of one or more unattached radios in an event or exercise Section 6.2.91 */
public class UnattachedIdentifierTest {
  public UnattachedIdentifierTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.UnattachedIdentifier openDis = new edu.nps.moves.dis7.UnattachedIdentifier();
    com.phyzicsz.dis7.UnattachedIdentifier dis = new UnattachedIdentifier();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
