/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * The unique designation of one or more unattached radios in an event or
 * exercise Section 6.2.91
 */
public class UnattachedIdentifierTest {

	@Test
	public void testUnattachedIdentifier() {
	}
}