/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * container class not in specification
 */
public class UnsignedDISIntegerTest {

	@Test
	public void testUnsignedDISInteger() {
	}
}