// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// container class not in specification
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * container class not in specification */
public class UnsignedDISIntegerTest {
  public UnsignedDISIntegerTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.UnsignedDISInteger openDis = new edu.nps.moves.dis7.UnsignedDISInteger();
    com.phyzicsz.dis7.UnsignedDISInteger dis = new UnsignedDISInteger();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
