// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// the variable datum type, the datum length, and the value for that variable datum type. NOT COMPLETE. Section 6.2.93
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * the variable datum type, the datum length, and the value for that variable datum type. NOT COMPLETE. Section 6.2.93 */
public class VariableDatumTest {
  public VariableDatumTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.VariableDatum openDis = new edu.nps.moves.dis7.VariableDatum();
    com.phyzicsz.dis7.VariableDatum dis = new VariableDatum();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
