// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// specification of additional information associated with an entity or detonation, not otherwise accounted for in a PDU 6.2.94.1
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * specification of additional information associated with an entity or detonation, not otherwise accounted for in a PDU 6.2.94.1 */
public class VariableParameterTest {
  public VariableParameterTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.VariableParameter openDis = new edu.nps.moves.dis7.VariableParameter();
    com.phyzicsz.dis7.VariableParameter dis = new VariableParameter();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
