/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * specification of additional information associated with an entity or
 * detonation, not otherwise accounted for in a PDU 6.2.94.1
 */
public class VariableParameterTest {

	@Test
	public void testVariableParameter() {
	}
}