// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Relates to radios. NOT COMPLETE. Section 6.2.94
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Relates to radios. NOT COMPLETE. Section 6.2.94 */
public class VariableTransmitterParametersTest {
  public VariableTransmitterParametersTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.VariableTransmitterParameters openDis = new edu.nps.moves.dis7.VariableTransmitterParameters();
    com.phyzicsz.dis7.VariableTransmitterParameters dis = new VariableTransmitterParameters();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
