/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Relates to radios. NOT COMPLETE. Section 6.2.94
 */
public class VariableTransmitterParametersTest {

	@Test
	public void testVariableTransmitterParameters() {
	}
}