/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * the variable datum type, the datum length, and the value for that variable
 * datum type. NOT COMPLETE. Section 6.2.93
 */
public class VariableDatumTest {

	@Test
	public void testVariableDatum() {
	}
}