// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Three double precision floating point values, x, y, and z. Used for world coordinates Section 6.2.97.
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Three double precision floating point values, x, y, and z. Used for world coordinates Section 6.2.97. */
public class Vector3DoubleTest {
  public Vector3DoubleTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.Vector3Double openDis = new edu.nps.moves.dis7.Vector3Double();
    com.phyzicsz.dis7.Vector3Double dis = new Vector3Double();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
