// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Three floating point values, x, y, and z. Section 6.2.95
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Three floating point values, x, y, and z. Section 6.2.95 */
public class Vector3FloatTest {
  public Vector3FloatTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.Vector3Float openDis = new edu.nps.moves.dis7.Vector3Float();
    com.phyzicsz.dis7.Vector3Float dis = new Vector3Float();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
