/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Two floating point values, x, y
 */
public class Vector2FloatTest {

	@Test
	public void testVector2Float() {
	}
}