/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Three floating point values, x, y, and z. Section 6.2.95
 */
public class Vector3FloatTest {

	@Test
	public void testVector3Float() {
	}
}