/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Three double precision floating point values, x, y, and z. Used for world
 * coordinates Section 6.2.97.
 */
public class Vector3DoubleTest {

	@Test
	public void testVector3Double() {
	}
}