// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// Two floating point values, x, y
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Two floating point values, x, y */
public class Vector2FloatTest {
  public Vector2FloatTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.Vector2Float openDis = new edu.nps.moves.dis7.Vector2Float();
    com.phyzicsz.dis7.Vector2Float dis = new Vector2Float();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
