/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * Operational data for describing the vectoring nozzle systems Section 6.2.96
 */
public class VectoringNozzleSystemTest {

	@Test
	public void testVectoringNozzleSystem() {
	}
}