/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis7;

import org.junit.Test;

/**
 * abstract superclass for fire and detonation pdus that have shared
 * information. Section 7.3 COMPLETE
 */
public class WarfareFamilyPduTest {

	@Test
	public void testWarfareFamilyPdu() {
	}
}