// /**
// * Autogenerated by dis-codegen
// *
// DO NOT EDIT DIRECTLY
// */
// abstract superclass for fire and detonation pdus that have shared information. Section 7.3 COMPLETE
package com.phyzicsz.dis7;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * abstract superclass for fire and detonation pdus that have shared information. Section 7.3 COMPLETE */
public class WarfareFamilyPduTest {
  public WarfareFamilyPduTest() {
  }

  @Test
  public void wirelineSizeTest() {
    edu.nps.moves.dis7.WarfareFamilyPdu openDis = new edu.nps.moves.dis7.WarfareFamilyPdu();
    com.phyzicsz.dis7.WarfareFamilyPdu dis = new WarfareFamilyPdu();
    int openDisSize = openDis.getMarshalledSize();
    int localSize = dis.wirelineSize();
    assertEquals(openDisSize,localSize);
  }
}
