language: java
before_install:
  - chmod +x build.sh
script: ./build.sh
jdk:
  - openjdk11
branches:
  only:
    - master
    - development
addons:
  sonarcloud:
    organization: "phyzicsz"
    token:
      secure: "**************************" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

