language: java
before_install:
- chmod +x build.sh
script:
- "./build.sh"
jdk:
- openjdk11
branches:
  only:
  - master
  - development
addons:
  sonarcloud:
    organization: phyzicsz
    
env:
  global:
  - secure: Ed408RhuKQ2ZpDvCB9nj5ZBI5KoObSoY0TspE/J+jPv4uyt4PUQH9UOb0ZBjjtTHDKOicr0EFe2SfbvUcW2rXU/banlE7ZAMJH2cCeF9C9YI+57tGK3+hQ7gXUc3jDa2IG6XDjWoP1S3cCCPkfLAXluY4pxo7LdA0BDWP3oAQRNj8sWzIbHolgJD8+Q2d6x965o8HPBFrZfZpg7r+Bxd452y+Q6LmSXK10Rou+E09WSJCDqn2gwQTEjepvuOn460a3/P6/s3hK2HmyYJBuW1vuFaNm5oJiw6bST0vTtoLUh3jxquAAOW0rUq1dou3b9Qm8xdMOdQO7XLSbWSfvFjJWQ0LBMjsKctiRf2loE2ABXhJJ9t4Z3+jp92iYGHZr/4y5RYHNhHbGnvo2FYTeSkrrzfZoP2eF0+NhzEEA13Z/B/fRkYQMprWtTQd12+BKZwJZfKmvbZlze5ec4VCBWVG7Mnf7/RZmTYYZsJJ5w9hJwszT4YwIbbCCWUot/wuvvfQO7rV4lpzy3u7fE0UpWFJxH+tTcb+xJgdIOhTV5MPEYer84U2LryzFKnbr1bkKyC6k9gka5McdIN3fqfIWl+SC6reLrasPNEdptFh0wkKlsLCO2c5Fcx2ildAuR1b6y2Y8r1+6BhICF2kw78QrXDz5OG9IILfZ9U4UKvxVJQeJI=

