/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis.codegen;

import java.nio.ByteBuffer;
import static org.junit.Assert.assertTrue;
import org.junit.Test;

/**
 * information about a specific UA emmtter. Section 6.2.2.
 */
public class AcousticEmitterTest {

	@Test
	public void testAcousticEmitter() {
            edu.nps.moves.dis7.AcousticEmitter emitter1 = new edu.nps.moves.dis7.AcousticEmitter();
            emitter1.setAcousticIDNumber((short)1);
            emitter1.setAcousticSystemName(10);
            emitter1.setAcousticFunction((short)2);
            
            
            ByteBuffer buffer1 = ByteBuffer.allocate(256);
            emitter1.marshal(buffer1);
            buffer1.flip();
            
//            com.phyzicsz.dis.AcousticEmitter emitter2 = new com.phyzicsz.dis.AcousticEmitter();
//            emitter2.setAcousticIDNumber((short)1);
//            emitter2.setAcousticSystemName(10);
//            emitter2.setAcousticFunction((short)2);
//
//            ByteBuffer buffer2 = ByteBuffer.allocate(256);
//            emitter2.serialize(buffer2);
//            buffer2.flip();
//            
//            int compare = buffer2.compareTo(buffer1);
//            
//            
//            com.phyzicsz.dis.AcousticEmitter emitter3 = new com.phyzicsz.dis.AcousticEmitter();
//            emitter3.deserialize(buffer2);
//            
//            boolean same = emitter3.equals(emitter2);
//            
//            int z = 0;
            
	}
}