/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis;

import org.junit.Test;
import org.junit.Assert.assertEquals;

/**
 * The unique designation of each aggregate in an exercise is specified by an
 * aggregate identifier record. The aggregate ID is not an entity and shall not
 * be treated as such. Section 6.2.3.
 */
public class AggregateIdentifierTest {

	@Test
	public void testAggregateIdentifier() {
		edu.nps.moves.dis7.AggregateIdentifier openDis = new edu.nps.moves.dis7.AggregateIdentifier();
		com.phyzicsz.dis.AggregateIdentifier local = new com.phyzicsz.dis.AggregateIdentifier();
		int openDisSize = openDis.getMarshalledSize();
		int localSize = local.wirelineSize();
		assertEquals(openDisSize, localSize);
	}
}