/**
* Autogenerated by dis-codegen
*
DO NOT EDIT DIRECTLY
*/
package com.phyzicsz.dis;

import org.junit.Test;
import org.junit.Assert.assertEquals;

/**
 * A Simulation Address record shall consist of the Site Identification number
 * and the Application Identification number. Section 6.2.79
 */
public class SimulationAddressTest {

	@Test
	public void testSimulationAddress() {
		edu.nps.moves.dis7.SimulationAddress openDis = new edu.nps.moves.dis7.SimulationAddress();
		com.phyzicsz.dis.SimulationAddress local = new com.phyzicsz.dis.SimulationAddress();
		int openDisSize = openDis.getMarshalledSize();
		int localSize = local.wirelineSize();
		assertEquals(openDisSize, localSize);
	}
}